logging:
  level:
    com.magic.mirror: DEBUG


feign:
  openWeather:
    url: "http://api.openweathermap.org/data/2.5"
    apiKey: "1e96dde2ea8dafa8adb0446b7294bbe4"
    units: "metric"

  nameDay:
    url: "https://api.abalin.net"
    country: "sk"
    token: "Chrome"

  qoutes:
    url: "https://quotepark.com/api/quotes/"
    language_code: "sk"

